### PR TITLE
Reformat project with `clang-format`

### LINKED ISSUE #188: Reformat project with ClangFormat
Continuing discussion from https://github.com/rmcolq/pandora/pull/186#pullrequestreview-303213542

> The PR is actually small (if I did not miss anything). What makes it very large is the Clang formatting (I guess >90% of the lines are formatting changes, not code logic changes). It made reviewing complicated since sometimes I would skip some parts of the review by rapidly scanning the changes which seemed like only Clang formatting changes.

> I guess we acknowledged this after making these commits (some months ago) and decided to make a big PR with only Clang formatting changes, and then proceed from there. I am willing to do this as soon as possible so that it is easier to review future code, but we still have some WIP branches in pandora. If we apply the Clang formatting in the whole code base now, I guess we will get a bunch of conflicts when merging these branches, which might be hard to solve. So we are thinking on applying Clang Formatting when the code is in a stable state (i.e. probably when finishing the paper).

> **What do you think about this? When should we apply Clang formatting?**

So team, when are we going to do this? I think we have dumped a lot of issues in the "waiting-until-the-code-is-stable" basket. I vote for biting the bullet and doing it.

### PR DESCRIPTION
**Pull request by mbhall88**
Reformatted all files with `clang-format` [closes #188 ].

Additionally, added a format check step to the Travis CI build (and tweaked some other things).

I have also set up a pre-commit git hook locally. What this does it run a check before you can commit locally to see if you have formatted all of the files associated with the commit.

Add the following code snippet inside the pandora project directory as `.git/hooks/pre-commit`

```sh
#!/bin/sh
# pre-commit hook that checks the files being commited have been formatted with 
# clang-format and the project style
git diff --cached --name-only --diff-filter=ACMRT |
  grep -E '\.cpp|\.h' |
  xargs -n1 clang-format -style=file -output-replacements-xml |
  grep "<replacement " >/dev/null
if [ $? -ne 1 ]; then
    echo "PreCommitError: The .cpp and .h files you are trying to commit did not match clang-format required style."
    exit 1
fi
```
and then run `chmod +x .git/hooks/pre-commit`

Also, if you haven't set it up already, you can tell CLion to use `clang-format as it's engine for reformatting https://www.jetbrains.com/help/clion/clangformat-as-alternative-formatter.html

### CODE REVIEW

**Comment by mbhall88** [comment]
Tagged as WIP as the formatting has messed up some of the namespaces I think and now it won't compile... Will try and fix quickly.

**Comment by mbhall88** [comment]
Working towards updating the CI [#158 ] I have set up three stages for the CI to pass: Lint, Build, and Test.  

As this PR is just concerned with formatting I have only put real commands in the Lint stage in a job called Format. If we also want to add a linting job within the stage (using `clang-tidy`) we can do that later too. For now, the Build and Test stages only have `echo` statements. So, although they pass, they don't do anything at this stage. That is work for a separate PR.

With this set up Lint gets run first, so if the code being pushed hasn't been formatted to our specified style in `.clang-format` then the build will fail.  

@rmcolq I have enabled all of this on my Travis fork, but I think you might need to also update your Travis settings for pandora so that it runs Travis on PRs etc.

**Comment by rmcolq** [comment]
When you say you have Travis working locally, do you still have an `install.sh` file? Looks like I need to make one again for this to run on PR

**Comment by mbhall88** [comment]
> When you say you have Travis working locally, do you still have an `install.sh` file? Looks like I need to make one again for this to run on PR

No, there isn't an `install.sh` anymore. You wont be able to get it to run on this PR as the travis config doesn't exist on your branch. Also, as `dev` will be quite different from `master` I'm not sure if maybe we need to specify something about branches in the travis settings. Let me take a look.

**Comment by mbhall88** [comment]
So by default Travis should run on all branches provided that option is selected in the Travis Web interface settings (normally on by default). If we only want to build on specific branches we can [specify that in the config] (https://docs.travis-ci.com/user/customizing-the-build/#safelisting-or-blocklisting-branches).

**Pull request merged**
