### PR TITLE
Update singularity docker

### PR DESCRIPTION
**Pull request by rmcolq**
Addresses issue #191 about fixing singularity image (removes it and replaces with docker image)

Looks like an old commit has been added to this branch too. I will remove it.

### CODE REVIEW

**Comment by rmcolq** [comment]
Actually it looks like i have to make a new commit and reverse it. Do we want the extended information (it was added in another branch for debugging) or shall I go ahead and put back to normal?

**Comment by leoisl** [comment]
I am fine with keeping the coverage info to the header of consensus fastq, this will be relevant to the identification of FP genes

**Comment by leoisl** [comment]
Oops, you just undid the commit, it is fine also, we can merge it later! and this PR is better now!

**Comment by rmcolq** [comment]
Ok to merge?

**Comment by leoisl** [comment]
seems fine for me!

**Pull request merged**
